services:
  - postgresql
before_script:
  - psql -c 'create database ex_admin_test;' -U postgres
  - nohup phantomjs --wd &
language: elixir
elixir:
  - 1.7
otp_release:
  - 21.0
sudo: false
script: mix test --include integration:true
